#!/usr/bin/env python3
"""Generate Make and C configuration artifacts from Kconfig."""

from __future__ import annotations

import argparse
from pathlib import Path

import kconfiglib


def bool_value(value: str) -> str:
    return "1" if value == "y" else "0"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--defconfig", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--auto-conf", type=Path, required=True)
    parser.add_argument("--autoconf-h", type=Path, required=True)
    arguments = parser.parse_args()

    kconfig = kconfiglib.Kconfig(str(arguments.root / "Kconfig"))
    kconfig.load_config(str(arguments.defconfig))
    arguments.config.parent.mkdir(parents=True, exist_ok=True)
    arguments.auto_conf.parent.mkdir(parents=True, exist_ok=True)
    arguments.autoconf_h.parent.mkdir(parents=True, exist_ok=True)
    kconfig.write_config(str(arguments.config))

    make_lines = ["# Generated by tools/config/generate.py. Do not edit."]
    header_lines = ["#pragma once", "/* Generated by tools/config/generate.py. */"]
    for name, symbol in sorted(kconfig.syms.items()):
        if not name:
            continue
        if symbol.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            value = bool_value(symbol.str_value)
        else:
            value = symbol.str_value
        make_lines.append(f"CONFIG_{name} := {value}")
        header_lines.append(f"#define CONFIG_{name} {value}")

    arguments.auto_conf.write_text("\n".join(make_lines) + "\n")
    arguments.autoconf_h.write_text("\n".join(header_lines) + "\n")


if __name__ == "__main__":
    main()
