#!/usr/bin/env python3
"""Generate x86_64 ISR vector stubs for exception handling.

Exceptions 0-7, 9, 15-16, 18-31 have no error code.
Exceptions 8, 10-14, 17 have error codes pushed by the CPU.
"""

# Exceptions without error codes
NO_ERROR_EXCEPTIONS = {0, 1, 2, 3, 4, 5, 6, 7, 9, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31}

def generate_vectors():
    lines = []
    lines.append("/* x86_64 exception vector stubs - auto-generated by gen_vectors.py */")
    lines.append("")
    lines.append(".section .text.vectors")
    lines.append(".align 16")
    lines.append(".global sys_amd64_vectors_start")
    lines.append(".global sys_amd64_vectors_end")
    lines.append("")
    lines.append("sys_amd64_vectors_start:")
    lines.append("")

    for vec in range(256):
        lines.append(f".align 8")
        lines.append(f".global asm_exception_{vec}")
        lines.append(f"asm_exception_{vec}:")

        if vec not in NO_ERROR_EXCEPTIONS and vec < 32:
            # CPU already pushed error code, just push vector
            lines.append(f"    push ${vec}")
        else:
            # No error code from CPU, push dummy 0 then vector
            lines.append(f"    push $0")
            lines.append(f"    push ${vec}")

        lines.append(f"    jmp common_handler")
        lines.append("")

    lines.append(".align 16")
    lines.append("common_handler:")
    lines.append("    /* Save general-purpose registers (order matches frame_t) */")
    lines.append("    push %rax")
    lines.append("    push %rcx")
    lines.append("    push %rdx")
    lines.append("    push %rbx")
    lines.append("    push %rbp")
    lines.append("    push %rsi")
    lines.append("    push %rdi")
    lines.append("    push %r8")
    lines.append("    push %r9")
    lines.append("    push %r10")
    lines.append("    push %r11")
    lines.append("    push %r12")
    lines.append("    push %r13")
    lines.append("    push %r14")
    lines.append("    push %r15")
    lines.append("")
    lines.append("    /* Call handler with rsp pointing to frame_t */")
    lines.append("    mov %rsp, %rdi")
    lines.append("    call sys_amd64_exception_handler")
    lines.append("")
    lines.append("    /* Handler should not return; if it does, halt */")
    lines.append("    cli")
    lines.append("    hlt")
    lines.append("    jmp .")
    lines.append("")
    lines.append(".align 8")
    lines.append("sys_amd64_vectors_end:")

    return "\n".join(lines)

if __name__ == "__main__":
    print(generate_vectors())
