#!/usr/bin/env python3
"""Generate x86_64 ISR vector stubs for exception handling.

Exceptions 0-7, 9, 15-16, 18-31 have no error code.
Exceptions 8, 10-14, 17 have error codes pushed by the CPU.

Writes two files rather than one: 256 stubs plus common_handler is ~1804
lines, over this project's 1200-line boundary-check limit for a single .S
file, and splitting the range roughly in half keeps each generated file
comfortably under that regardless of future changes to the stub body.
sys_amd64_enter_user is NOT part of this generator's output -- it is
hand-written thread-entry code (src/arch/amd64/boot/entry.S), unrelated to
exception vectoring, and was only ever appended to the single old vectors.S
by hand after the fact.
"""
import sys

NO_ERROR_EXCEPTIONS = {0, 1, 2, 3, 4, 5, 6, 7, 9, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31}
SPLIT = 128


def stub(vec):
    lines = [".align 8", f".global asm_exception_{vec}", f"asm_exception_{vec}:"]
    if vec not in NO_ERROR_EXCEPTIONS and vec < 32:
        lines.append(f"    push ${vec}")
    else:
        lines.append("    push $0")
        lines.append(f"    push ${vec}")
    lines.append("    jmp common_handler")
    lines.append("")
    return lines


def generate_low():
    lines = []
    lines.append("/* x86_64 exception vector stubs 0-%d - auto-generated by gen_vectors.py */" % (SPLIT - 1))
    lines.append("")
    lines.append(".section .text.vectors")
    lines.append(".align 16")
    lines.append(".global sys_amd64_vectors_start")
    lines.append("")
    lines.append("sys_amd64_vectors_start:")
    lines.append("")
    for vec in range(SPLIT):
        lines.extend(stub(vec))
    return "\n".join(lines)


def generate_high():
    lines = []
    lines.append("/* x86_64 exception vector stubs %d-255 plus the shared trap handler" % SPLIT)
    lines.append(" * they all jump to -- auto-generated by gen_vectors.py */")
    lines.append("")
    lines.append(".section .text.vectors")
    lines.append(".align 16")
    lines.append(".global sys_amd64_vectors_end")
    # common_handler must be .global: it is defined here but jumped to from
    # vectors_low.S, a separate translation unit -- without this the two
    # would link, but only by accident of both landing in the same final
    # binary rather than through a resolved symbol reference, and a local
    # (non-.global) label is not visible across object files at all, so the
    # jmp in vectors_low.S would fail to link.
    lines.append(".global common_handler")
    lines.append("")
    for vec in range(SPLIT, 256):
        lines.extend(stub(vec))
    lines.append(".align 16")
    lines.append("common_handler:")
    lines.append("    /* Save general-purpose registers (order matches frame_t) */")
    for reg in ["rax", "rcx", "rdx", "rbx", "rbp", "rsi", "rdi", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15"]:
        lines.append(f"    push %{reg}")
    lines.append("")
    lines.append("    /* Call handler with rsp pointing to frame_t */")
    lines.append("    mov %rsp, %rdi")
    lines.append("    call sys_amd64_exception_handler")
    lines.append("")
    lines.append("    /* Handler should not return; if it does, halt */")
    lines.append("    cli")
    lines.append("    hlt")
    lines.append("    jmp .")
    lines.append("")
    lines.append(".align 8")
    lines.append("sys_amd64_vectors_end:")
    return "\n".join(lines)


def generate_table():
    """Address table: sys_amd64_vector_table[N] = &asm_exception_N.

    A separate generated file rather than folded into vectors_low.S/
    vectors_high.S: it references all 256 stub labels regardless of which
    of those two files defines them, and keeping it apart means neither
    stub file needs to know the other exists.
    """
    lines = []
    lines.append("/* Address table for the 256 ISR stubs -- auto-generated by gen_vectors.py.")
    lines.append(" * Read by sys::arch::exception::initialize_idt() to build the real IDT. */")
    lines.append("")
    lines.append(".section .rodata")
    lines.append(".align 8")
    lines.append(".global sys_amd64_vector_table")
    lines.append("sys_amd64_vector_table:")
    for vec in range(256):
        lines.append(f"    .quad asm_exception_{vec}")
    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit("usage: gen_vectors.py <vectors_low.S> <vectors_high.S> <vectors_table.S>")
    with open(sys.argv[1], "w") as f:
        f.write(generate_low() + "\n")
    with open(sys.argv[2], "w") as f:
        f.write(generate_high() + "\n")
    with open(sys.argv[3], "w") as f:
        f.write(generate_table() + "\n")
