[system]
name = "zilch-development"
abi = "sys-v1"

[[program]]
name = "init"
path = "/bin/init"
role = "root-task"
required = true

[[program]]
name = "domain-manager"
path = "/bin/domain-manager"
role = "domain-manager"
required = false
